apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: web
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
    - name: redis-container
      image: redis
      ports:
        - containerPort: 88
    - name: memcached-container
      image: memcashed
      ports:
        - containerPort: 8080
    - name: consul-container
      image: consul
      ports:
        - containerPort: 80
