apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx-rs-service
  name: nginx-rs-service
spec:
  selector:
    app: nginx-rs-pod
  ports:
  - name: k8-service
    nodePort: 31000
    port: 80
    targetPort: 80
    protocol: TCP
  type: NodePort
